name: sil_todo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  get: ^4.6.5
  json_serializable: ^6.7.1
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
